services:
  app:
    container_name: fivechat
    image: itsfimall/fivechat:latest
    ports:
      - "${HOST_PORT}:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL:-./data/fivechat.db}
      AUTH_SECRET: ${AUTH_SECRET}
      ADMIN_CODE: ${ADMIN_CODE}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
      EMAIL_AUTH_STATUS: ${EMAIL_AUTH_STATUS}
    volumes:
      - sqlite_data:/app/data
    restart: unless-stopped
    networks:
      - my-network

volumes:
  sqlite_data:

networks:
  my-network:
    driver: bridge
