name: Docker

on:
  workflow_dispatch:
    inputs:
      version:
        description: '镜像版本号'
        required: false
        default: 'latest'
      environment:
        description: '部署环境'
        required: false
        default: 'production'
        type: choice
        options:
        - production
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Generate date tag
        id: date
        run: echo "date=$(date +'%y%m%d')" >> $GITHUB_OUTPUT
        
      - name: Generate short SHA
        id: sha
        run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
     
      # 设置 QEMU 以支持多平台构建
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
     
      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host
     
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
     
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/fivechat
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.date.outputs.date }}
            type=raw,value=${{ steps.sha.outputs.short_sha }}
            type=raw,value=${{ github.event.inputs.version }},enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=FiveChat
            org.opencontainers.image.description=FiveChat Application
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.date.outputs.date }}
     
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ github.workflow }}-${{ github.ref }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}-${{ github.ref }}
          build-args: |
            ENVIRONMENT=${{ github.event.inputs.environment || 'production' }}
            
      - name: Image digest
        run: echo ${{ steps.build.outputs.digest }}